apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-agent-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
    processors:

    exporters:
      jaeger/2:
        endpoint: simplest-collector-headless.opentelemetry-operator-system.svc:14250
        insecure: true

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [jaeger/2]
