apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-all-in-one-inmemory
spec:
  strategy: allInOne
  allInOne:
    options: 
      log-level: debug
    resources: {}
    collector:
      options:
        log-level: trace
  agent:
    options:  
      log-level: debug
    resources: {}
  collector:
    options: 
      log-level: trace
    resources: {}
  sampling:
    options: {}
  storage:
    type:
    options: {}
  query:
    options: {}
    resources: {}
  ingester:
    options: {}
    resources: {}
  options: {}
