apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: otel-flask
  namespace: knative-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/targetUtilizationPercentage: "80"
    spec:
      containerConcurrency: 10
      containers:
        - image: docker.io/haoruibing/otel-flask:latest
          ports:
            - containerPort: 5000
