apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-python-flask
  namespace: openshift-gitops
spec:
  destination:
    namespace: argocd-python-flask
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: kubernetes
    repoURL: https://github.com/ruibinghao/otel-hello-world.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true